# Generated by Django 2.0.7 on 2018-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
