# Generated by Django 2.0.7 on 2018-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
